package com.applovin.impl.sdk;

import com.immersion.hapticmediasdk.HapticContentSDK;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import mf.javax.xml.XMLConstants;

class bx {
    public static final bz f232A;
    public static final bz f233B;
    public static final bz f234C;
    public static final bz f235D;
    public static final bz f236E;
    public static final bz f237F;
    public static final bz f238G;
    public static final bz f239H;
    public static final bz f240I;
    public static final bz f241J;
    public static final bz f242K;
    public static final bz f243L;
    public static final bz f244M;
    public static final bz f245N;
    public static final bz f246O;
    public static final bz f247P;
    public static final bz f248Q;
    public static final bz f249R;
    public static final bz f250S;
    public static final bz f251T;
    public static final bz f252U;
    public static final bz f253V;
    public static final bz f254W;
    public static final bz f255X;
    public static final bz f256Y;
    public static final bz f257Z;
    public static final bz f258a;
    public static final bz aA;
    public static final bz aB;
    public static final bz aC;
    public static final bz aD;
    public static final bz aE;
    public static final bz aF;
    public static final bz aG;
    public static final bz aH;
    public static final bz aI;
    public static final bz aJ;
    public static final bz aK;
    public static final bz aL;
    public static final bz aM;
    public static final bz aN;
    public static final bz aO;
    public static final bz aP;
    public static final bz aQ;
    public static final bz aR;
    public static final bz aS;
    public static final bz aT;
    public static final bz aU;
    public static final bz aV;
    public static final bz aW;
    public static final bz aX;
    public static final bz aY;
    public static final bz aZ;
    public static final bz aa;
    public static final bz ab;
    public static final bz ac;
    public static final bz ad;
    public static final bz ae;
    public static final bz af;
    public static final bz ag;
    public static final bz ah;
    public static final bz ai;
    public static final bz aj;
    public static final bz ak;
    public static final bz al;
    public static final bz am;
    public static final bz an;
    public static final bz ao;
    public static final bz ap;
    public static final bz aq;
    public static final bz ar;
    public static final bz as;
    public static final bz at;
    public static final bz au;
    public static final bz av;
    public static final bz aw;
    public static final bz ax;
    public static final bz ay;
    public static final bz az;
    public static final bz f259b;
    public static final bz ba;
    public static final bz bb;
    public static final bz bc;
    public static final bz bd;
    public static final bz be;
    public static final bz bf;
    public static final bz bg;
    public static final bz bh;
    public static final bz bi;
    public static final bz bj;
    public static final bz bk;
    public static final bz bl;
    public static final bz bm;
    public static final bz bn;
    public static final bz bo;
    private static final List bp;
    private static final List bq;
    public static final bz f260c;
    public static final bz f261d;
    public static final bz f262e;
    public static final bz f263f;
    public static final bz f264g;
    public static final bz f265h;
    public static final bz f266i;
    public static final bz f267j;
    public static final bz f268k;
    public static final bz f269l;
    public static final bz f270m;
    public static final bz f271n;
    public static final bz f272o;
    public static final bz f273p;
    public static final bz f274q;
    public static final bz f275r;
    public static final bz f276s;
    public static final bz f277t;
    public static final bz f278u;
    public static final bz f279v;
    public static final bz f280w;
    public static final bz f281x;
    public static final bz f282y;
    public static final bz f283z;

    static {
        bp = Arrays.asList(new Class[]{Boolean.class, Float.class, Integer.class, Long.class, String.class});
        bq = new ArrayList();
        f258a = m156a("is_disabled", Boolean.valueOf(false));
        f259b = m156a("honor_publisher_settings", Boolean.valueOf(true));
        f260c = m156a("device_id", XMLConstants.NULL_NS_URI);
        f261d = m156a("publisher_id", XMLConstants.NULL_NS_URI);
        f262e = m156a("device_token", XMLConstants.NULL_NS_URI);
        f263f = m156a("submit_data_retry_count", Integer.valueOf(1));
        f264g = m156a("vr_retry_count", Integer.valueOf(1));
        f265h = m156a("fetch_ad_retry_count", Integer.valueOf(1));
        f266i = m156a("is_verbose_logging", Boolean.valueOf(false));
        f267j = m156a("api_endpoint", "http://d.applovin.com/");
        f268k = m156a("adserver_endpoint", "http://a.applovin.com/");
        f269l = m156a("get_retry_delay", Long.valueOf(10000));
        f270m = m156a("hash_algorithm", "SHA-1");
        f271n = m156a("short_hash_size", Integer.valueOf(16));
        f272o = m156a("http_connection_timeout", Integer.valueOf(30000));
        f273p = m156a("fetch_ad_connection_timeout", Integer.valueOf(30000));
        f274q = m156a("http_socket_timeout", Integer.valueOf(20000));
        f275r = m156a("ad_session_minutes", Integer.valueOf(60));
        f276s = m156a("ad_request_parameters", XMLConstants.NULL_NS_URI);
        f277t = m156a("ad_refresh_enabled", Boolean.valueOf(true));
        f278u = m156a("ad_refresh_seconds", Long.valueOf(120));
        f279v = m156a("mrec_ad_refresh_enabled", Boolean.valueOf(true));
        f280w = m156a("mrec_ad_refresh_seconds", Long.valueOf(120));
        f281x = m156a("leader_ad_refresh_enabled", Boolean.valueOf(true));
        f282y = m156a("leader_ad_refresh_seconds", Long.valueOf(120));
        f283z = m156a("plugin_version", XMLConstants.NULL_NS_URI);
        f232A = m156a("ad_preload_enabled", Boolean.valueOf(true));
        f233B = m156a("ad_resource_caching_enabled", Boolean.valueOf(true));
        f234C = m156a("resource_cache_prefix", "https://vid.applovin.com/,https://pdn.applovin.com/,https://img.applovin.com/,https://d.applovin.com/,https://assets.applovin.com/,https://cdnjs.cloudflare.com/,http://vid.applovin.com/,http://pdn.applovin.com/,http://img.applovin.com/,http://d.applovin.com/,http://assets.applovin.com/,http://cdnjs.cloudflare.com/");
        f235D = m156a("ad_auto_preload_sizes", "BANNER,INTER");
        f236E = m156a("ad_auto_preload_incent", Boolean.valueOf(true));
        f237F = m156a("is_tracking_enabled", Boolean.valueOf(true));
        f238G = m156a("force_back_button_enabled_always", Boolean.valueOf(false));
        f239H = m156a("countdown_color", "#C8FFFFFF");
        f240I = m156a("close_fade_in_time", Integer.valueOf(400));
        f241J = m156a("show_close_on_exit", Boolean.valueOf(true));
        f242K = m156a("text_incent_prompt_title", "Earn a Reward");
        f243L = m156a("text_incent_prompt_body", "Would you like to watch a video for a reward?");
        f244M = m156a("text_incent_prompt_yes_option", "Watch Now");
        f245N = m156a("text_incent_prompt_no_option", "No Thanks");
        f246O = m156a("text_incent_completion_title", "Video Reward");
        f247P = m156a("text_incent_completion_body_success", "You have earned a reward!");
        f248Q = m156a("text_incent_completion_body_quota_exceeded", "You have already earned the maximum reward for today.");
        f249R = m156a("text_incent_completion_body_reward_rejected", "Your reward was rejected.");
        f250S = m156a("text_incent_completion_body_network_failure", "We were unable to contact the rewards server. Please try again later.");
        f251T = m156a("text_incent_completion_close_option", "Okay");
        f252U = m156a("show_incent_prepopup", Boolean.valueOf(true));
        f253V = m156a("show_incent_postpopup", Boolean.valueOf(true));
        f254W = m156a("preload_capacity_banner", Integer.valueOf(1));
        f255X = m156a("preload_capacity_mrec", Integer.valueOf(1));
        f256Y = m156a("preload_capacity_inter", Integer.valueOf(1));
        f257Z = m156a("preload_capacity_leader", Integer.valueOf(1));
        aa = m156a("preload_capacity_incent", Integer.valueOf(2));
        ab = m156a("dismiss_video_on_error", Boolean.valueOf(true));
        ac = m156a("precache_delimiters", ")]',");
        ad = m156a("close_button_size_graphic", Integer.valueOf(27));
        ae = m156a("close_button_size_video", Integer.valueOf(30));
        af = m156a("close_button_top_margin_graphic", Integer.valueOf(10));
        ag = m156a("close_button_right_margin_graphic", Integer.valueOf(10));
        ah = m156a("close_button_top_margin_video", Integer.valueOf(8));
        ai = m156a("close_button_right_margin_video", Integer.valueOf(4));
        aj = m156a("force_back_button_enabled_poststitial", Boolean.valueOf(false));
        ak = m156a("force_back_button_enabled_close_button", Boolean.valueOf(false));
        al = m156a("close_button_touch_area", Integer.valueOf(0));
        am = m156a("is_video_skippable", Boolean.valueOf(false));
        an = m156a("cache_cleanup_enabled", Boolean.valueOf(false));
        ao = m156a("cache_file_ttl_seconds", Long.valueOf(86400));
        ap = m156a("cache_max_size_mb", Integer.valueOf(-1));
        aq = m156a("preload_merge_init_tasks_incent", Boolean.valueOf(true));
        ar = m156a("preload_merge_init_tasks_inter", Boolean.valueOf(true));
        as = m156a("submit_postback_timeout", Integer.valueOf(HapticContentSDK.f1228b04440444044404440444));
        at = m156a("submit_postback_retries", Integer.valueOf(10));
        au = m156a("widget_imp_tracking_delay", Integer.valueOf(2000));
        av = m156a("draw_countdown_clock", Boolean.valueOf(true));
        aw = m156a("countdown_clock_size", Integer.valueOf(32));
        ax = m156a("countdown_clock_stroke_size", Integer.valueOf(4));
        ay = m156a("countdown_clock_text_size", Integer.valueOf(28));
        az = m156a("ad_auto_preload_native", Boolean.valueOf(true));
        aA = m156a("widget_fail_on_slot_count_diff", Boolean.valueOf(true));
        aB = m156a("video_zero_length_as_computed", Boolean.valueOf(false));
        aC = m156a("video_countdown_clock_margin", Integer.valueOf(10));
        aD = m156a("video_countdown_clock_gravity", Integer.valueOf(83));
        aE = m156a("preload_capacity_widget", Integer.valueOf(1));
        aF = m156a("widget_latch_timeout_ms", Integer.valueOf(500));
        aG = m156a("android_gc_on_widget_detach", Boolean.valueOf(true));
        aH = m156a("lhs_close_button_video", Boolean.valueOf(false));
        aI = m156a("lhs_close_button_graphic", Boolean.valueOf(false));
        aJ = m156a("lhs_skip_button", Boolean.valueOf(true));
        aK = m156a("countdown_toggleable", Boolean.valueOf(false));
        aL = m156a("native_batch_precache_count", Integer.valueOf(1));
        aM = m156a("mute_controls_enabled", Boolean.valueOf(false));
        aN = m156a("allow_user_muting", Boolean.valueOf(true));
        aO = m156a("mute_button_size", Integer.valueOf(32));
        aP = m156a("mute_button_margin", Integer.valueOf(10));
        aQ = m156a("mute_button_gravity", Integer.valueOf(85));
        aR = m156a("max_apps_to_send", Integer.valueOf(0));
        aS = m156a("is_app_list_shared", Boolean.valueOf(false));
        aT = m156a("qq", Boolean.valueOf(false));
        aU = m156a("hw_accelerate_webviews", Boolean.valueOf(false));
        aV = m156a("mute_videos", Boolean.valueOf(false));
        aW = m156a("event_tracking_endpoint", "http://rt.applovin.com/pix");
        aX = m156a("top_level_events", "landing,checkout,iap");
        aY = m156a("events_enabled", Boolean.valueOf(true));
        aZ = m156a("force_ssl", Boolean.valueOf(false));
        ba = m156a("postback_service_max_queue_size", Integer.valueOf(100));
        bb = m156a("max_postback_attempts", Integer.valueOf(3));
        bc = m156a("click_overlay_enabled", Boolean.valueOf(false));
        bd = m156a("click_overlay_color", "#66000000");
        be = m156a("click_tracking_retry_count", Integer.valueOf(3));
        bf = m156a("click_tracking_retry_delay", Integer.valueOf(2000));
        bg = m156a("click_tracking_timeout", Integer.valueOf(HapticContentSDK.f1228b04440444044404440444));
        bh = m156a("android_click_spinner_size", Integer.valueOf(50));
        bi = m156a("android_click_spinner_style", Integer.valueOf(16973853));
        bj = m156a("android_dismiss_inters_on_click", Boolean.valueOf(false));
        bk = m156a("android_require_external_storage_permission", Boolean.valueOf(true));
        bl = m156a("android_drop_nomedia", Boolean.valueOf(true));
        bm = m156a("native_auto_cache_preload_resources", Boolean.valueOf(true));
        bn = m156a("sanitize_webview", Boolean.valueOf(false));
        bo = m156a("webview_package_name", "com.google.android.webview");
    }

    private static bz m156a(String str, Object obj) {
        if (obj == null) {
            throw new IllegalArgumentException("No default value specified");
        } else if (bp.contains(obj.getClass())) {
            bz bzVar = new bz(obj, null);
            bq.add(bzVar);
            return bzVar;
        } else {
            throw new IllegalArgumentException("Unsupported value type: " + obj.getClass());
        }
    }

    public static Collection m157a() {
        return Collections.unmodifiableList(bq);
    }

    public static int m158b() {
        return bq.size();
    }
}
